### ISSUE TITLE
Javascript comments are escaped incorrectly

### ISSUE THREAD

**Issue by basvis** [ozum/replace-between#1]
When replacing between comments in javascript files the comment characters are escaped incorrectly causing a syntax error in the regular expression:

SyntaxError: Invalid regular expression: /(/*\s*?API BEGIN\s*?*/.*?[\r\n]+)[\s\S]*?(/*\s*?API END\s*?*/)/: Nothing to repeat

**Comment by basvis** [comment]
@ozum Created pull request for this issue: https://github.com/ozum/replace-between/pull/2

**Comment by ozum** [comment]
Thanks.

**Comment by basvis** [comment]
@ozum Could you make a new release with this fix? Thanks!

**Comment by ozum** [comment]
@basvis. I just released both git and npm.
